all:
	g++ -o main mgtk.cpp `pkg-config --cflags --libs gtkmm-2.4 opencv`
#	g++ -std=c++11 -o main mgtk.cpp `pkg-config --cflags --libs gtkmm-2.4 opencv`
#	g++ -o main mgtk.cpp `pkg-config --cflags --libs gtkmm-3.0 opencv`
#	g++ -o main mgtk.cpp `pkg-config --cflags --libs gtk+-2.0 gmodule-2.0 opencv`

clean:
	rm main
